# Generated by Django 3.1.6 on 2021-04-17 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('query', models.CharField(max_length=1000, null=True)),
                ('response', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('salary', models.IntegerField(default=0)),
                ('totalVacancy', models.IntegerField(default=0)),
                ('features', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('dob', models.CharField(max_length=20, null=True)),
                ('cv', models.FileField(null=True, upload_to='static/useruploads')),
                ('citizenship', models.ImageField(null=True, upload_to='static/usercitizen')),
                ('qualification', models.CharField(max_length=1000)),
                ('applied', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('response', models.CharField(max_length=1000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suser', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.vacancy')),
            ],
        ),
    ]
