# Generated by Django 3.1.6 on 2021-04-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('query', models.CharField(max_length=1000, null=True)),
                ('response', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
